# -*- coding: utf-8 -*-
"""AMAZON SALES ANALYSIS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XLD80R80IlIBPvwM-BH1O5yB949DMsjI
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Set visualization style
sns.set(style="whitegrid")
plt.rcParams['figure.figsize'] = (12, 6)

try:
    # Attempt to load the dataset
    # Note: 'encoding' parameter is often needed for this specific dataset due to special characters
    df = pd.read_csv('Amazon Sale Report.csv', encoding='unicode_escape')
    print("✅ Dataset Loaded Successfully!")
    print("Columns in dataset:", df.columns.tolist())

    # Display first 5 rows
    display(df.head())

except FileNotFoundError:
    print("❌ Error: File not found. Please upload 'Amazon Sale Report.csv' to the Colab files section.")

# 1. Drop completely empty columns (like New, PendingS if they are empty)
df.drop(columns=['index', 'New', 'PendingS'], errors='ignore', inplace=True)

# 2. Handle Missing Values in Amount
# If Amount is NaN, fill with 0 (or drop if you prefer stricter analysis)
df['Amount'].fillna(0, inplace=True)

# 3. Drop rows where essential shipping info is missing (optional but recommended)
df.dropna(subset=['ship-city', 'ship-state'], inplace=True)

# 4. Fix Date Column
# Coerce errors will turn unparseable dates into NaT (Not a Time), then we drop them
df['Date'] = pd.to_datetime(df['Date'], errors='coerce')

# 5. Standardize 'ship-state' (making all uppercase to avoid "Goa" vs "GOA" duplicates)
df['ship-state'] = df['ship-state'].str.upper()

print("✅ Data Cleaning Complete.")
print(f"Total Rows remaining: {len(df)}")

# Extract Month and Year for grouping
df['Month'] = df['Date'].dt.to_period('M')

# Aggregate Sales by Month
monthly_sales = df.groupby('Month')['Amount'].sum()

# Plotting
plt.figure(figsize=(12, 6))
monthly_sales.plot(kind='line', marker='o', color='b', linewidth=2)
plt.title('Total Sales Revenue Over Time', fontsize=16)
plt.xlabel('Month', fontsize=12)
plt.ylabel('Revenue (Amount)', fontsize=12)
plt.grid(True)
plt.show()

# Print Summary
print(f"Total Revenue: {df['Amount'].sum():,.2f}")
print(f"Total Orders: {len(df)}")

# 1. Top Product Categories by Quantity
plt.figure(figsize=(12, 6))
sns.countplot(data=df, x='Category', order=df['Category'].value_counts().index, palette='viridis')
plt.title('Number of Orders per Product Category', fontsize=16)
plt.xlabel('Category')
plt.ylabel('Count of Orders')
plt.xticks(rotation=45) # Rotate labels for better readability
plt.show()

# 2. Size Distribution
plt.figure(figsize=(10, 5))
sns.countplot(data=df, x='Size', order=df['Size'].value_counts().index, palette='pastel')
plt.title('Distribution of Sizes Sold', fontsize=16)
plt.show()

# Insight Calculation
top_cat = df['Category'].value_counts().idxmax()
print(f"Most Popular Category: {top_cat}")

# Create a subplot (1 row, 2 columns)
fig, ax = plt.subplots(1, 2, figsize=(15, 6))

# 1. Fulfillment Method
fulfillment_counts = df['Fulfilment'].value_counts()
ax[0].pie(fulfillment_counts, labels=fulfillment_counts.index, autopct='%1.1f%%', startangle=140, colors=['#ff9999','#66b3ff'])
ax[0].set_title('Distribution of Fulfillment Methods')

# 2. B2B vs Retail
b2b_counts = df['B2B'].value_counts()
ax[1].pie(b2b_counts, labels=['Retail (Consumer)', 'B2B (Business)'], autopct='%1.1f%%', startangle=140, colors=['#99ff99','#ffcc99'])
ax[1].set_title('Customer Segmentation (B2B vs B2C)')

plt.show()

# Aggregate sales count by State
top_states = df['ship-state'].value_counts().head(10)

plt.figure(figsize=(12, 6))
sns.barplot(x=top_states.index, y=top_states.values, palette='coolwarm')
plt.title('Top 10 States by Order Volume', fontsize=16)
plt.xlabel('State')
plt.ylabel('Number of Orders')
plt.xticks(rotation=45)
plt.show()

